# Generated by Django 5.1.15 on 2026-06-16 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('tags', models.JSONField(default=list)),
                ('genre', models.JSONField(blank=True, default=list)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('personality', models.JSONField(default=list)),
                ('occupation', models.CharField(max_length=120)),
                ('race', models.CharField(max_length=80)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('quote', models.TextField(blank=True)),
                ('memory_summary', models.TextField(blank=True)),
                ('avatar', models.URLField(max_length=500)),
                ('cover', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('genre', models.JSONField(default=list)),
                ('character_count', models.PositiveIntegerField(default=0)),
                ('cover', models.URLField(max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='api.character')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('character', 'Character'), ('narration', 'Narration'), ('system', 'System')], max_length=16)),
                ('content', models.TextField()),
                ('timestamp', models.CharField(blank=True, max_length=32)),
                ('emotion_delta', models.CharField(blank=True, max_length=32)),
                ('interaction_type', models.CharField(blank=True, max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('detail', models.TextField(blank=True)),
                ('emotion', models.CharField(max_length=80)),
                ('date', models.DateField()),
                ('importance', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('quote', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('thumbnail', models.URLField(blank=True, max_length=500)),
                ('dday', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='api.character')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='api.world'),
        ),
        migrations.CreateModel(
            name='EmotionAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=32)),
                ('value', models.FloatField(default=0)),
                ('color', models.CharField(max_length=16)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotions', to='api.character')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('character', 'key')},
            },
        ),
    ]
