# Generated by Django 5.1.15 on 2026-06-16 05:48

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='ArchiveRecord',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('object_key', models.CharField(max_length=512, unique=True)),
                ('source_type', models.CharField(choices=[('chat', 'Chat'), ('memory', 'Memory'), ('character', 'Character'), ('world', 'World'), ('emotion', 'Emotion'), ('session', 'Session'), ('interaction', 'Interaction')], max_length=32)),
                ('source_id', models.CharField(max_length=128)),
                ('character_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('content_type', models.CharField(default='application/json', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'character_id'], name='api_archive_source__a2a63d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RagChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_id', models.CharField(db_index=True, max_length=64)),
                ('source_type', models.CharField(max_length=32)),
                ('source_id', models.CharField(max_length=128)),
                ('chunk_text', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('importance', models.FloatField(default=0.5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='api.archiverecord')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='rag_chunk_embedding_hnsw', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
