# Generated by Django 5.1.15 on 2026-06-16 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_archiverecord_ragchunk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingContent',
            fields=[
                ('key', models.SlugField(max_length=64, primary_key=True, serialize=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='characters_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='world',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worlds_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archiverecord',
            name='source_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('memory', 'Memory'), ('character', 'Character'), ('world', 'World'), ('emotion', 'Emotion'), ('session', 'Session'), ('interaction', 'Interaction'), ('content', 'Content'), ('scenario', 'Scenario'), ('relationship', 'Relationship'), ('studio', 'Studio')], max_length=32),
        ),
        migrations.CreateModel(
            name='RelationshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('summary', models.TextField(blank=True)),
                ('delta', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_events_center', to='api.character')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_events_created', to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_events', to='api.world')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CharacterScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenario_id', models.SlugField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prompt', models.TextField(blank=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='api.character')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['character_id', 'scenario_id'],
                'unique_together': {('character', 'scenario_id')},
            },
        ),
        migrations.CreateModel(
            name='RelationshipEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('friend', 'Friend'), ('alliance', 'Alliance'), ('enemy', 'Enemy'), ('lover', 'Lover'), ('family', 'Family'), ('ex_lover', 'ExLover'), ('neutral', 'Neutral')], default='friend', max_length=16)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('weight', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_edges_created', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_edges_out', to='api.character')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_edges_in', to='api.character')),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_edges', to='api.world')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['world_id', 'source_id'], name='api_relatio_world_i_811686_idx')],
            },
        ),
    ]
